---
title: "Historical vs Currrent"
output: html_document
---

### The Contiguous United States

##### Ecosystems are constantly changing and adapting whether it's slowly and minutely or abrubtly and drastically. Changes  


#### Comparison of ecosystems historically vs now

```{r}
library(sf)
library(ggplot2)
library(DataCombine)
library(reshape2)
library(plotly)

comp <- UsedData

#renaming columns

colnames(comp)[colnames(comp)=="ORIGINAL"] <- "ACRES_HIST"

colnames(comp)[colnames(comp)=="NotAG_DEV"] <- "ACRES_CURR"

colnames(comp)[colnames(comp)=="BPS_NAME"] <- "CLASSNAME"

#reordering by classname

comp <- arrange(comp, CLASSNAME)

#removing weird row

#comp <- comp[-c(393), -c(5)]

#assigning NA values to 0 in AG and DEV rows

comp[c("AG", "DEV")][is.na(comp[c("AG", "DEV")])] <- 0



#adding diff column

comp$DIFF <- abs(comp$ACRES_HIST - comp$ACRES_CURR)

#adding percent change column

comp$PER_CHANGE <- round((comp$DIFF / comp$ACRES_HIST) * 100, 2)

#comp$PER_CHANGE[!is.finite(comp$PER_CHANGE)] <- 100

#head(comp$PER_CHANGE)

#head(comp)
#tail(comp)

#p <- plot_ly(comp, x = ~ACRES_CURR, y = ~DIFF, text = ~paste("Ecosystem: ", CLASSNAME, "<br> Historical Acres: ", ACRES_HIST))

#p

#totalAcres <- sum(comp$ACRES_HIST)

#comp <- comp[!(sum(comp$ACRES_HIST) >=  ]

#comp.long <- melt(comp)

#colnames(comp.long)[colnames(comp.long) == "value"] <- "ACRES"


#eco <- ggplot(comp.long, aes(fill = variable, y = ACRES, x = reorder(CLASSNAME, ACRES, function(x){sum(x)}))) + geom_bar(position = "dodge", stat="identity") + coord_flip() + xlab("Ecosystem")


#eco

```



```{r}
library(dplyr)
library(tidyr)
#Preparing Map Data for use

allDataMap <- MapData

#removing the value and us_140 columns
allDataMap <- allDataMap[-c(1, 4)]



#taking out all values with urban in the name

urbanMap <- allDataMap %>%
    filter(
      grepl('Urban', DESCRIPTIO)
    )

#changing label and description to urban for simplicity
urbanMap$DESCRIPTIO <- 'Urban'
urbanMap$LABEL <- 'Urban'

#summing the count column by GEOID10 column
urbanCntys <- urbanMap[c(1, 2)]

urbanMap <- urbanMap[-c(1)]

urbanCntys <- urbanCntys %>%
    group_by(CNTYS) %>%
      summarise(COUNT = sum(COUNT))

urbanMap <- merge(urbanMap, urbanCntys, by = 'CNTYS')

urbanMap <- urbanMap[!duplicated(urbanMap),]




#doing the same thing but for AG

agMap <- allDataMap %>%
    filter(
      grepl('Agriculture', DESCRIPTIO)
    )

#changing label and description to urban for simplicity
agMap$DESCRIPTIO <- 'Agriculture'
agMap$LABEL <- 'Agriculture'

#summing the count column by GEOID10 column
urbanCntys <- agMap[c(1, 2)]

agMap <- agMap[-c(1)]

urbanCntys <- urbanCntys %>%
    group_by(CNTYS) %>%
      summarise(COUNT = sum(COUNT))

agMap <- merge(agMap, urbanCntys, by = 'CNTYS')

agMap <- agMap[!duplicated(agMap),]





#doing more or less the same thing but for everything not agriculture or urban

naturalMap <- allDataMap %>% 
    filter(
      !grepl("Agriculture|Urban", DESCRIPTIO)
    )

#changing label and description to urban for simplicity
naturalMap$DESCRIPTIO <- 'Natural'
naturalMap$LABEL <- 'Natural'

#summing the count column by GEOID10 column
naturalCntys <- naturalMap[c(1, 2)]

naturalMap <- naturalMap[-c(1)]

naturalCntys <- naturalCntys %>%
    group_by(CNTYS) %>%
      summarise(COUNT = sum(COUNT))

naturalMap <- merge(naturalMap, naturalCntys, by = 'CNTYS')

naturalMap <- naturalMap[!duplicated(naturalMap),]
    


#starting to merge all data back into a complete map
completeMap <- naturalMap


completeMap <- rbind(completeMap, urbanMap, agMap)

#taking out DESCRIPTIO column

completeMap$DESCRIPTIO <- NULL


#creating a  total county acres column

countyTotal <- select( completeMap, CNTYS, COUNT)

#summing each count for each label

countyTotal <- countyTotal %>%
  group_by(CNTYS) %>%
    summarise(COUNT = sum(COUNT))

#renaming to TOTALS
colnames(countyTotal)[colnames(countyTotal)=="COUNT"] <- "TOTAL"


#adding column back in so each row has a total for whichever county it has
completeMap <- merge(completeMap, countyTotal, by = 'CNTYS')


#making completeMap data set long to be able to add to shape file

completeMap <- spread(completeMap, key = LABEL, value = COUNT)


#rename columns to make more sense (I'm making them say ACRES because I'm going to change them to acres later but for now I'm leaving it as the original count value)

colnames(completeMap)[colnames(completeMap)=="Agriculture"] <- "ACRES_AG"

colnames(completeMap)[colnames(completeMap)=="Natural"] <- "ACRES_NAT"

colnames(completeMap)[colnames(completeMap)=="Urban"] <- "ACRES_URBAN"

#math to add percent columns

completeMap$PERCENT_AG <- round(completeMap$ACRES_AG/completeMap$TOTAL *100, 2) 

completeMap$PERCENT_URBAN <- round(completeMap$ACRES_URBAN/completeMap$TOTAL *100, 2) 

completeMap$PERCENT_NAT <- round(completeMap$ACRES_NAT/completeMap$TOTAL *100, 2) 


#changing acres columns to acutal acres values using the conversion of 0.222

completeMap$ACRES_AG <- completeMap$ACRES_AG *0.222

completeMap$ACRES_NAT <- completeMap$ACRES_NAT *0.222

completeMap$ACRES_URBAN <- completeMap$ACRES_URBAN *0.222

completeMap$TOTAL <- completeMap$TOTAL *0.222


#making the data wide



#exporting data as a .csv
#write.csv(completeMap,"C:\\Users\\User\\Desktop\\completeMap.csv", row.names = TRUE)

```



```{r}
library(sf)
library(dplyr)
library(leaflet)



#Qick Map

#read da data

usMap <- st_read(dsn = "./tl_2019_us_county.shp", layer ="tl_2019_us_county", stringsAsFactors = FALSE)

#stateFP <- usMap$STATEFP

usMap <- usMap[!usMap$STATEFP %in% c("02", "15", "72", "66", "78", "60", "69", "64", "68", "70", "74"),]

usMap <- usMap[!usMap$STATEFP %in% c("81", "84", "86", "87", "89", "71", "76", "95", "79"),]

counties <- st_read("tl_2019_us_county.shp")

# renaming GEOID10 to GEOID in completeMap data set to prepare for merge
colnames(completeMap)[colnames(completeMap)=="GEOID10"] <- "GEOID"

#add leading zeos to any FIPS code that's less than 5 digits long to get a good match.
completeMap$GEOID <- formatC(completeMap$GEOID, width = 5, format = "d", flag = "0")


usMap$NAME <- NULL
usMap$NAMELSAD <- NULL
usMap$LSAD <- NULL
usMap$CLASSFP <- NULL
usMap$MTFCC <- NULL
usMap$CSAFP <- NULL
usMap$CBSAFP <- NULL
usMap$METDIVFP <- NULL
usMap$FUNCSTAT  <- NULL
usMap$ALAND  <- NULL
usMap$AWATER  <- NULL


leafMap <- merge(usMap, completeMap, by = "GEOID")
#make a jankey map (will have AK and other areas so will look too spread out, but you get the idea)

 
#making a map

#ggplot() +

  #geom_sf(data = leafMap, fill="#69b3a2", color="grey") +

  #theme_void()
```

```{r}
library(htmltools)
library(viridis)
library(dplyr)
library(leaflet)
#plot(usMap)



#colnames(leafMap@data)[colnames(leafMap@data)=="ACRES_AG"] <- "ACRES"

#filteredData <- completeMap[-c(6, 7, 10, 9)]

#making a color Palette
bin <- c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100)

# sf layer has inconsistent datum (+proj=longlat +datum=NAD83 +no_defs ).
#Need '+proj=longlat +datum=WGS84'

pal <- colorNumeric(palette = "viridis", domain = range(0,100), reverse = TRUE, na.color = "red")

lab = sprintf("<strong>%s County</strong><br/>%g%% Natural <br/>%g Natural Acres", leafMap$CNTYS, leafMap$PERCENT_NAT, leafMap$ACRES_NAT) %>%
    lapply(HTML)


leaflet(data = leafMap) %>%
  #addTiles() %>%
    addPolygons(weight = 1,
        smoothFactor = 0.02,
        fillOpacity = 0.9,
        color = ~pal(PERCENT_NAT),
        highlight = highlightOptions(
          weight = 3,
          color = "#666",
          fillOpacity = 1,
          bringToFront = TRUE),
        label = lab,
        labelOptions =labelOptions(textsize = "15px")) %>%
      
    addLegend(pal = pal,
        values = ~PERCENT_NAT,
        bins = bin,
        opacity = 0.7,
        title = NULL,
       position = "bottomright")
```



